"""Tests for extracted-profile output writers."""

from __future__ import annotations

import h5py
import numpy as np

from lst_tools import __version__
from lst_tools.extract._types import SampledProfiles
from lst_tools.extract._writers import write_profiles_hdf5


def test_write_profiles_hdf5_records_generator_provenance(tmp_path) -> None:
    """Extracted HDF5 files should identify the generating lst-tools version."""

    # build one minimal profile with the standard output fields
    profile_values = np.array([[0.0, 1.0]])
    profiles = SampledProfiles(
        station_x=np.array([0.5]),
        station_y=np.array([0.0]),
        station_s=np.array([0.5]),
        eta=np.array([0.0, 1.0]),
        sample_x=profile_values,
        sample_y=profile_values,
        uvel=profile_values,
        vvel=profile_values,
        wvel=profile_values,
        temp=profile_values,
        pres=profile_values,
        rho=profile_values,
    )
    output_path = tmp_path / "extracted_baseflow.hdf5"

    # write and reopen the file to verify persisted root attributes
    write_profiles_hdf5(output_path, profiles, attrs={})

    with h5py.File(output_path, "r") as hdf5_file:
        assert hdf5_file.attrs["generated by"] == "lst-tools"
        assert hdf5_file.attrs["generator version"] == __version__
