"""lst-tools clean — remove generated files from parsing, tracking, or spectra setup."""


# --------------------------------------------------
# load necessary modules
# --------------------------------------------------
from __future__ import annotations

import logging
import shutil
from pathlib import Path
from typing import Annotated

import typer


# --------------------------------------------------
# set up logger
# --------------------------------------------------
logger = logging.getLogger(__name__)


# --------------------------------------------------
# helpers
# --------------------------------------------------
def _collect_targets(
    directory: Path,
    patterns: list[str],
) -> list[Path]:
    """Glob *directory* for each pattern and return a sorted, deduplicated list."""
    hits: dict[Path, None] = {}
    for pat in patterns:
        for p in sorted(directory.glob(pat)):
            hits[p] = None
    return list(hits)


def _remove(targets: list[Path]) -> int:
    """Delete every path in *targets* (files or directories). Return count."""
    removed = 0
    for p in targets:
        if p.is_dir():
            shutil.rmtree(p)
            logger.info("removed directory %s", p)
        else:
            p.unlink()
            logger.info("removed file %s", p)
        removed += 1
    return removed


def _confirm_and_remove(targets: list[Path], force: bool) -> None:
    """Print what will be removed, prompt unless *force*, then delete."""
    if not targets:
        typer.echo("nothing to clean")
        raise typer.Exit()

    typer.echo("the following will be removed:")
    for p in targets:
        label = "dir " if p.is_dir() else "    "
        typer.echo(f"  {label}{p}")

    if not force:
        typer.confirm("proceed?", abort=True)

    n = _remove(targets)
    typer.echo(f"removed {n} item(s)")


# --------------------------------------------------
# parsing clean
# --------------------------------------------------
def cmd_clean_parsing(
    directory: Annotated[
        Path,
        typer.Option("--dir", "-d", help="Directory to clean (default: current directory)."),
    ] = Path("."),
    name: Annotated[
        str,
        typer.Option("--name", "-n", help="Input-deck filename to remove."),
    ] = "lst_input.dat",
    force: Annotated[
        bool,
        typer.Option("--force", "-f", help="Skip confirmation prompt."),
    ] = False,
) -> None:
    """Remove files generated by ``lst-tools setup parsing``.

    Removes the LST input deck and any HPC run scripts (``run.*.*``)
    from the target directory.
    """
    directory = directory.resolve()

    # collect targets: input deck + HPC run scripts
    targets: list[Path] = []

    input_deck = directory / name
    if input_deck.exists():
        targets.append(input_deck)

    # HPC scripts follow the pattern run.<scheduler>.<hostname>
    targets.extend(_collect_targets(directory, ["run.*.*"]))

    _confirm_and_remove(targets, force)


# --------------------------------------------------
# tracking clean
# --------------------------------------------------
def cmd_clean_tracking(
    directory: Annotated[
        Path,
        typer.Option("--dir", "-d", help="Directory to clean (default: current directory)."),
    ] = Path("."),
    force: Annotated[
        bool,
        typer.Option("--force", "-f", help="Skip confirmation prompt."),
    ] = False,
) -> None:
    """Remove files generated by ``lst-tools setup tracking``.

    Removes all ``kc_*/`` case directories, the ``run_jobs.sh`` launcher
    script, and the ``debug/`` directory.
    """
    directory = directory.resolve()

    # collect targets: kc_* dirs, launcher script, debug dir
    targets = _collect_targets(directory, ["kc_*"])

    launcher = directory / "run_jobs.sh"
    if launcher.exists():
        targets.append(launcher)

    debug_dir = directory / "debug"
    if debug_dir.is_dir():
        targets.append(debug_dir)

    _confirm_and_remove(targets, force)


# --------------------------------------------------
# spectra clean
# --------------------------------------------------
def cmd_clean_spectra(
    directory: Annotated[
        Path,
        typer.Option("--dir", "-d", help="Directory to clean (default: current directory)."),
    ] = Path("."),
    force: Annotated[
        bool,
        typer.Option("--force", "-f", help="Skip confirmation prompt."),
    ] = False,
) -> None:
    """Remove files generated by ``lst-tools setup spectra``.

    Removes all ``x_*/`` case directories and the ``run_cases.sh``
    launcher script.
    """
    directory = directory.resolve()

    # collect targets: x_* dirs, launcher script
    targets = _collect_targets(directory, ["x_*"])

    launcher = directory / "run_cases.sh"
    if launcher.exists():
        targets.append(launcher)

    _confirm_and_remove(targets, force)
